version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        patterns:
          - '*eslint*'
          - '*prettier*'
          - '*typescript*'
          - '*vitest*'
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '*eslint*'
          - '*prettier*'
          - '*typescript*'
          - '*vitest*'
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
